### ISSUE TITLE
Not working with latest version

### ISSUE THREAD

**Issue by dilip-dhankecha** [Mindinventory/Golang-PDF-to-Image-Converter#1]

**Comment by NStart** [comment]
I encountered this problem when i exec go run main.go.
err:github.com/karmdip-mi/go-fitz: build constraints exclude all Go files in /root/go/pkg/mod/github.com/karmdip-mi/go-fitz@v0.0.0-20210316172528-f0a07eb93909

**Comment by bipinmishra97** [comment]
> I encountered this problem when i exec go run main.go. err:github.com/karmdip-mi/go-fitz: build constraints exclude all Go files in /root/go/pkg/mod/github.com/karmdip-mi/go-fitz@v0.0.0-20210316172528-f0a07eb93909

@NStart 
Just make sure in your `go ENV` below three variables are set as these values
```
CGO_ENABLED=1
GOARCH=386
GOGCCFLAGS=-m32
```
 
 I faced the same issue with the latest **go v1.21.6** in Ubuntu OS, but after setting the values of given above three parameters it is working fine for me now.
 
 You can set the value using the below command
 ```
set CGO_ENABLED=1
set GOARCH=386
set GOGCCFLAGS=-m32
 ```
 
 Thanks!
